language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly

notifications:
  - email: false

after_success:
  - julia -e 'Pkg.clone("https://github.com/thofma/Documenter.jl.git"); Pkg.checkout("Documenter", "build_non_master")'
  - DOCUMENTER_DEBUG=true julia -e 'cd(Pkg.dir("Hecke")); include(joinpath("docs", "make.jl"))'
