site_name:           Hecke.jl
repo_url:            https://github.com/thofma/Hecke.jl
site_description:    Hecke
site_author:         Tommy Hofmann
theme:               readthedocs

pages:
- Introduction:        index.md
- Orders:              build/Orders.md
- Maximal Orders:      build/MaximalOrders.md

markdown_extensions:
- tables
- fenced_code
- mdx_math:
    enable_dollar_delimiter: True

extra_javascript: ['mathjaxhelper.js', 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

