site_name:           Hecke.jl
repo_name:           thofma/Hecke
repo_url:            https://github.com/thofma/Hecke.jl
site_description:    Hecke
site_author:         Tommy Hofmann
theme:               cinder

#extra:
#  palette:
#    primary: 'indigo'
#    accent: 'light blue'

pages:
- Getting Started:      index.md
- Number fields:
  - Introduction:       numberfields/introduction.md
  - Orders:             numberfields/orders.md
  - Maximal Orders:     numberfields/maximalorders.md
#- Maximal Orders:
#    - Introduction:    build/MaximalOrders/Introduction.md
#    - Creation:        build/MaximalOrders/Creation.md
#    - Elements:        build/MaximalOrders/Elements.md
#    - Ideals:          build/MaximalOrders/Ideals.md
#- Orders:              build/Orders.md

extra_css:
    - assets/Documenter.css

markdown_extensions:
- codehilite
- extra
- tables
- fenced_code
- mdx_math:
    enable_dollar_delimiter: True
- admonition

docs_dir: 'build'

extra_javascript: ['mathjaxhelper.js', 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

